WH-TalentSoft/Models/ViewTRAINEE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WH_TalentSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTRAINEE
    {
        public string Key { get; set; }
        public string Code_de_la_session { get; set; }
        public string Matricule { get; set; }
        public string Stagiaire { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Prévues { get; set; }
        public Nullable<int> Réalisées { get; set; }
        public Nullable<System.DateTime> mtime { get; set; }
        public string Pays { get; set; }
        public string DESC_PPC_Location { get; set; }
        public string Theme { get; set; }
        public string Type_de_formation { get; set; }
        public string Statut_de_la_session { get; set; }
        public Nullable<System.DateTime> Date_début_de_la_session { get; set; }
        public Nullable<System.DateTime> Date_fin_de_la_session { get; set; }
        public string Nom_formateur_de_la_session { get; set; }
        public string Prénom_formateur_de_la_session { get; set; }
        public string Nom_de_l_action { get; set; }
        public string Projet { get; set; }
        public string Code_emploi { get; set; }
        public string DESC_du_code_emploi { get; set; }
        public string Company { get; set; }
        public string Desc_of_company { get; set; }
        public Nullable<bool> Statut { get; set; }
        public string Etat_de_la_session { get; set; }
    }
}

WH-TalentSoft/Controllers/ViewSessionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WH_TalentSoft.Models;
using PagedList;

namespace WH_TalentSoft.Controllers
{
    public class ViewSessionsController : Controller
    {
        private Entities db = new Entities();


        public ActionResult Chat()
        {
            return View();
        }


        // GET: ViewSessions
        public ActionResult Index()
        {
            ViewBag.TypeFormation = db.ViewSESSION1.Where(t => t.Type_de_formation != null).Select(t => t.Type_de_formation).Distinct().ToList();
            ViewBag.StatutSession = db.ViewSESSION1.Where(t => t.Statut_de_la_session != null).Select(t => t.Statut_de_la_session).Distinct().ToList();
            ViewBag.Project = db.ViewSESSION1.Where(t => t.Projet != null).Select(t => t.Projet).Distinct().ToList();
            return View();
        }

        public ActionResult _ViewSession(int? page, string search1 = "", string search2 = "", string search3 = "", string search4 = "", string search5 = "", string search6 = "", string search7= "")
        {     
            var Formation = db.ViewSESSION1.AsQueryable();
            DateTime dateDebut;
            DateTime.TryParse(search1, out dateDebut);
            if (search1 != "") Formation = Formation.Where(s => s.Date_début_de_la_session.Value.CompareTo(dateDebut) == 0);
            if (search2 != "") Formation = Formation.Where(s => s.Code_de_la_session.Equals(search2));
            if (search3 != "") Formation = Formation.Where(s => s.Formateur.Contains(search3));
            if (search4 != "") Formation = Formation.Where(s => s.Projet.Contains(search4));
            if (search5 != "") Formation = Formation.Where(s => s.Type_de_formation.Equals(search5));
            if (search6 != "") Formation = Formation.Where(s => s.Statut_de_la_session.Equals(search6));
            if (search7 != "") Formation = Formation.Where(s => s.Etat_de_la_session.Equals(search7));
            var all = Formation.OrderBy(p => p.Date_début_de_la_session);   
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var resultToReturn = all.ToPagedList(pageNumber, pageSize);
            return PartialView(resultToReturn);       
        }

        public ActionResult Viewtrainee()
        {           
            ViewBag.pays = db.ViewTRAINEEs.Where(t => t.Pays != null).Select(t => t.Pays).Distinct().ToList();
            ViewBag.ppcLoc = db.ViewTRAINEEs.Where(t => t.DESC_PPC_Location != null).Select(t => t.DESC_PPC_Location).Distinct().ToList();
            
            return View();
        }
        public ActionResult ppcLocation(string pays)
        {          
            ViewBag.ppcLoc =(from m in db.ViewTRAINEEs where m.Pays==pays select m.DESC_PPC_Location ).Distinct().ToList();
            return Json(ViewBag.ppcLoc,JsonRequestBehavior.AllowGet);
        }

        public ActionResult _Viewtrainee(int? page, string search1 = "", string search2 = "", string search3 = "", string search4 = "")

        {
            var Formation = db.ViewTRAINEEs.AsQueryable();
            DateTime dateDebut;
            DateTime.TryParse(search1, out dateDebut);
            
            DateTime datefin;
            DateTime.TryParse(search2, out datefin);
            if (search1 != "") Formation = Formation.Where(s => s.Date_début_de_la_session.Value.CompareTo(dateDebut) == 0);
            if (search2 != "") Formation = Formation.Where(s => s.Date_fin_de_la_session.Value.CompareTo(datefin) == 0);
            if (search3 != "") Formation = Formation.Where(s => s.Pays.Equals(search3));
            if (search4 != "") Formation = Formation.Where(s => s.DESC_PPC_Location.Equals(search4));        
            var all = Formation.OrderBy(p => p.Date_début_de_la_session);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var resultToReturn = all.ToPagedList(pageNumber, pageSize);
            return PartialView(resultToReturn);
         
        }


        // GET: ViewSessions/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewSESSION1 viewSession = db.ViewSESSION1.Find(id);
            if (viewSession == null)
            {
                return HttpNotFound();
            }
            return View(viewSession);
        }

        // GET: ViewSessions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ViewSessions/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Key,ID,Action,Code_de_la_session,Type_de_formation,Projet,Formateur,Nombre_de_stagiaire,Statut_de_la_session,Date_début_de_la_session,Date_fin_de_la_session")] ViewSESSION1 viewSession)
        {
            if (ModelState.IsValid)
            {
                db.ViewSESSION1.Add(viewSession);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(viewSession);
        }

        // GET: ViewSessions/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewSESSION1 viewSession = db.ViewSESSION1.Find(id);
            if (viewSession == null)
            {
                return HttpNotFound();
            }
            return View(viewSession);
        }

        // POST: ViewSessions/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Key,ID,Action,Code_de_la_session,Type_de_formation,Projet,Formateur,Nombre_de_stagiaire,Statut_de_la_session,Date_début_de_la_session,Date_fin_de_la_session")] ViewSESSION1 viewSession)
        {
            if (ModelState.IsValid)
            {
                db.Entry(viewSession).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(viewSession);
        }

        // GET: ViewSessions/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewSESSION1 viewSession = db.ViewSESSION1.Find(id);
            if (viewSession == null)
            {
                return HttpNotFound();
            }
            return View(viewSession);
        }

        // POST: ViewSessions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ViewSESSION1 viewSession = db.ViewSESSION1.Find(id);
            db.ViewSESSION1.Remove(viewSession);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public FileContentResult DownloadCSV(string _search1 = "", string _search2 = "", string _search3 = "", string _search4 = "")
        {

            var EmployeeQry = db.ViewTRAINEEs.AsQueryable();
         
            DateTime dateDebut;
            DateTime.TryParse(_search1, out dateDebut);

            DateTime datefin;
            DateTime.TryParse(_search2, out datefin);

            string csv = string.Format("{0};{1};{2};{3};{4};{5};{6};{7};{8};{9};{10};{11};{12};{13};{14};{15};{16};{17};{18};{19};{20}\n",
                "Entity",
                "Projet",
                "Théme",
                "Action de Formation",
                "Nom du Formateur",
                "Prénom du Formateur",
                "Id de la Session",
                "Date de Début",
                "Date de Fin",
                "Status de la Session",
                "Type de Formation",
                "Stagiaire",
                "Matricule",
                "Date de la Sous-Session",
                "Status de Validation",
                "Nombre d'heures Réalisées",
                "Service",
                "Code Emploi",
                "Desc Du Code Emploi",
                "Company",
                "Desc Of Company");

            if (_search1 != "") EmployeeQry = EmployeeQry.Where(s => s.Date_début_de_la_session.Value.CompareTo(dateDebut) == 0);
            if (_search2 != "") EmployeeQry = EmployeeQry.Where(s => s.Date_fin_de_la_session.Value.CompareTo(datefin) == 0);
            if (_search3 != "") EmployeeQry = EmployeeQry.Where(s => s.Pays.Equals(_search3));
            if (_search4 != "") EmployeeQry = EmployeeQry.Where(s => s.DESC_PPC_Location.Equals(_search4));
            csv += string.Concat(from employee in EmployeeQry.OrderBy(p => p.Date_début_de_la_session).ToList()
                                 select string.Format("{0};{1};{2};{3};{4};{5};{6};{7};{8};{9};{10};{11};{12};{13};{14};{15};{16};{17};{18};{19};{20}\n",
                                 employee.Pays,
                                 employee.Projet,
                                 employee.Theme,
                                 employee.Nom_de_l_action,
                                 employee.Nom_formateur_de_la_session,

WH-TalentSoft/Views/ViewSessions/Create.cshtml
@model WH_TalentSoft.Models.ViewSESSION1

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ViewSession</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Action, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Action, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Action, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code_de_la_session, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code_de_la_session, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code_de_la_session, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type_de_formation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type_de_formation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type_de_formation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Projet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Projet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Projet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Formateur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Formateur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Formateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre_de_stagiaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre_de_stagiaire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_de_stagiaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Statut_de_la_session, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Statut_de_la_session, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Statut_de_la_session, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_début_de_la_session, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_début_de_la_session, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_début_de_la_session, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_fin_de_la_session, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_fin_de_la_session, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_fin_de_la_session, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WH-TalentSoft/Views/ViewSessions/Delete.cshtml
@model WH_TalentSoft.Models.ViewSESSION1

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ViewSession</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Action)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Action)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code_de_la_session)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code_de_la_session)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type_de_formation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type_de_formation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Projet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Projet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Formateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Formateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre_de_stagiaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre_de_stagiaire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Statut_de_la_session)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Statut_de_la_session)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_début_de_la_session)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_début_de_la_session)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_fin_de_la_session)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_fin_de_la_session)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WH-TalentSoft/Views/ViewSessions/Details.cshtml
@model WH_TalentSoft.Models.ViewSESSION1

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ViewSession</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Action)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Action)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code_de_la_session)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code_de_la_session)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type_de_formation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type_de_formation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Projet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Projet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Formateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Formateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre_de_stagiaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre_de_stagiaire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avancement_de_la_session)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Statut_de_validation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_début_de_la_session)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_début_de_la_session)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_fin_de_la_session)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_fin_de_la_session)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Key }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WH-TalentSoft/Views/ViewSessions/Viewtrainee.cshtml
@model WH_TalentSoft.ViewModel.HoursRealise
@{
    ViewBag.Title = "Viewtrainee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-icon" data-background-color="orange">
                    <i class="material-icons">view_list</i>
                </div>
                <div class="card-content">
                    <h4 class="card-title">Liste des sessions de formation</h4>
                    <legend>Filtre</legend>

                    @using (Html.BeginForm("_Viewtrainee", "ViewSessions", FormMethod.Get))
                    {
                        <div class="col-md-12">
                        <div class="form-group  col-md-2">
                            @Html.LabelFor(model => model.trainee.Date_début_de_la_session, htmlAttributes: new { @class = "label-control" })
                            @Html.EditorFor(model => model.search1, new { htmlAttributes = new { @class = "form-control datepicker", id = "search1" } })
                        </div>

                        <div class="form-group col-md-2">
                            @Html.LabelFor(model => model.trainee.Date_fin_de_la_session, htmlAttributes: new { @class = "label-control" })
                            @Html.EditorFor(model => model.search2, new { htmlAttributes = new { @class = "form-control datepicker", id = "search2" } })


                        </div>
                        <div class="form-group col-md-3">
                            <select class="selectpicker" id="search3">
                                <option value="" selected>Environement</option>
                                @foreach (var item in ViewBag.pays)
                                {
                                    <option value="@item">@item</option>
                                }
                            </select>
                        </div>
                        <div class="form-group col-md-3">
                            <select class="selectpicker" id="search4">
                                <option value="" selected>Selection</option>
                              
                            </select>
                        </div>


                        <div class="col-md-2">
                            <button id="btnsearch" type="submit" onclick="GetFilter()" class="btn btn-success btn-round btn-fab btn-fab-mini pull-right top">
                                <i class="material-icons">search</i>
                                <div class="ripple-container"></div>
                            </button>
                        </div>
                            </div>
                    
                    }
                   <div class="col-md-12">
                    <div class="card-content table-responsive table-full-width" id="test">
                        @{Html.RenderAction("_Viewtrainee", "ViewSessions", new { page = 1 });}
                    </div>
                       <div class="col-md-12">
                           <div class="col-md-4 col-md-offset-9 pull-right">
                               <button onclick="SaveCSV()" class="btn btn-success enr pull-right col-md-4">
                                   <span class="btn-label"><i class="material-icons">cloud_download</i></span> TÉLÉCHARGER
                                   <div class="ripple-container"></div>
                               </button>
                           </div>
                       </div>
                </div>
            </div>
        </div>
            @section scripts{

            <script>
                 $(document).on('change', "#search3", function () {
                    event.preventDefault();

                    var _search3 = $(this).val();    
                    $.ajax({
                        url: "@Url.Action("ppcLocation", "ViewSessions")?pays=" + _search3,
                        method: 'GET',
                        cache: false,
                        success: function (data) {  
                            var html = '<option value="" selected>Selection</option>';
                            for (var i = 0; i < data.length; i++) {
                                html += '<option value="' + data[i] + '">' + data[i] + '</option>';
                            }
                            $("#search4")
                                .html(html)
                                .selectpicker('refresh');                           
                        }
                    })

                });
            //$(".pagination").find("a").click(function () {
            //    event.preventDefault();
            //    $.get(event.target, function (success) {
            //        $("#test").html(success);
            //    });
            //    console.log(event.target.href);
            //    window.page = window.page || 1;
            //})
        function GetFilter() {
            event.preventDefault();
            var _search1 = $("#search1").val();
            var _search2 = $("#search2").val();
            var _search3 = $("#search3").val();
            var _search4 = $("#search4").val();

                window.page = 1;
                window.filter = '&search1=' + _search1 + '&search2=' + _search2 + '&search3=' + _search3 + '&search4=' + _search4;
                

            $.ajax({
                url: "@Url.Action("_Viewtrainee", "ViewSessions")",
                method: 'GET',
                cache: false,
                data: { search1: _search1, search2: _search2, search3: _search3, search4: _search4},
                success: function (result) {
                    $("#test").html(result);
                }
            });
                }




                function SaveCSV() {
                    event.preventDefault();
                    var _src1 = $("#search1").val();
                    var _src2 = $("#search2").val();
                    var _src3 = $("#search3").val();
                    var _src4 = $("#search4").val();

                        window.location = '@Url.Action("DownloadCSV", "ViewSessions")?_search1=' + _src1 + '&_search2=' + _src2 + '&_search3=' + _src3 + '&_search4=' + _src4;
                }
                </script>
            <script>
                $(".pagination").find("a").click(function (event)
                {
                    event.preventDefault();
                    $.get(
                        event.target,
                        
                        function (success) {
                            $("#test").html(success);
                        });
                })
            </script>
    
                }
       